### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by roflmaostc** [rdoelman/ZernikePolynomials.jl#2]
Hi!

Thanks for the great package!

I found a few performance and type stability bugs.
Do you accept a PR if I prepare one?

Best,

Felix

**Comment by roflmaostc** [comment]
I would be also willing to include more stuff like CI :)

I need that package for my work and I think it's worth it to fix a few things!

**Comment by roflmaostc** [comment]
See #3

**Comment by rdoelman** [comment]
Hey thanks for the feedback!

I'll try to go over your PRs this weekend.
