### ISSUE TITLE
Should we move this package to JuliaMath?

### ISSUE THREAD

**Issue by roflmaostc** [rdoelman/ZernikePolynomials.jl#4]
Thanks for merging this #3!

In terms of visibility and future development:
Should we move this package to [JuliaMath](https://github.com/JuliaMath) maybe?

I think, content-wise it would be nice to have it there.

Of course, it's your decision :smile: 

Best,
Felix

**Comment by roflmaostc** [comment]
@rdoelman I just wanted to bring this up again :smile: 

For example, I would like to make a new release containing the fixes

**Comment by timholy** [comment]
A new release is out. It seems the preference is to keep the package here.
