### ISSUE TITLE
Errors in creating constructors

### ISSUE THREAD

**Issue by sajjad88** [rdoelman/ZernikePolynomials.jl#8]
When I create 
`nm = NM(3, -3)`
 I get ERROR: UndefVarError: `NM` not defined. 

Similarly upon execution of 
`x = LinRange(-1,1,256)`
`ϕ = evaluatezernike(x, Noll.([2, 3]), [0.5, 0.3])`
I get ERROR: UndefVarError: `Noll` not defined.

**Comment by timholy** [comment]
The README had been updated but a new release had not been made. Try using v0.1.1 or later.
